version: '3'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - media:/code/media/
      - static:/code/static/
    ports:
      - "8080:8000"
    env_file:
      - environments.env

  frontend:
    build:
      context: ./frontend/
    ports:
      - "81:80"
    depends_on:
      - backend
    env_file:
      - environments.env

volumes:
  media:
  static:

