version: '3'

networks:
  proxiable:
    name: proxiable

services:
  backend:
    build:
      context: ./backend
    volumes:
      - media:/code/media/
      - static:/code/static/
    ports:
      - "8080:8000"

  frontend:
    build:
      context: ./frontend/
    ports:
      - "88:80"
    depends_on:
      - backend
  db:
    image: postgres:latest
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    networks:
      - proxiable


volumes:
  media:
  static:

