version: '3'

networks:
  proxiable:
    name: proxiable

services:
  backend:
    build:
      context: ./backend
    volumes:
      - media:/code/media/
      - static:/code/static/
    ports:
      - "8080:8000"

  frontend:
    build:
      context: ./frontend/
    ports:
      - "88:80"
    depends_on:
      - backend

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    networks:
      - proxiable
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "83:80"
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD:
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  media:
  static:
  local_pgdata:
  pgadmin-data:
