version: '3'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - media:/code/media/
      - staticfiles:/code/staticfiles/
    ports:
      - "8000:8000"
    env_file:
      - environments.env

  frontend:
    build:
      context: ./frontend/
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - environments.env

volumes:
  media:
  staticfiles:

