# Generated by Django 4.1.7 on 2023-06-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="column",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
