# Generated by Django 4.1.7 on 2023-06-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0003_photopositions_alter_photo_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photopositions",
            name="column_first",
        ),
        migrations.RemoveField(
            model_name="photopositions",
            name="column_second",
        ),
        migrations.RemoveField(
            model_name="photopositions",
            name="column_third",
        ),
        migrations.AddField(
            model_name="photopositions",
            name="positions",
            field=models.JSONField(null=True),
        ),
    ]
