# Generated by Django 4.1.7 on 2023-06-12 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0006_remove_photo_column_remove_photo_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="updated",
        ),
    ]
