# Generated by Django 4.1.7 on 2023-06-12 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0007_remove_photo_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photopositions",
            old_name="positions",
            new_name="columns",
        ),
    ]
