# Generated by Django 4.1.7 on 2023-07-29 11:48

import django.core.validators
from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0012_photo_updated_date_photopositions_updated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to=photos.models.upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(["jpg", "jpeg"])
                ],
                verbose_name="photos",
            ),
        ),
    ]
