# Generated by Django 4.1.7 on 2023-08-30 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import photos.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileRow",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "style_column",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "one column"),
                            (1, "two columns"),
                            (2, "three columns"),
                        ],
                        default=0,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        upload_to=photos.models.upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg"]
                            )
                        ],
                        verbose_name="photos",
                    ),
                ),
                ("column_id", models.IntegerField(default=1)),
                ("order", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "new"),
                            ("POSITIONED", "positioned at last configuration"),
                            ("NOT POSITIONED", "not positioned"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "style_column",
                    models.CharField(
                        choices=[
                            ("ONE_COLUMN", "one column"),
                            ("TWO_COLUMNS", "two columns"),
                            ("THREE_COLUMNS", "three columns"),
                        ],
                        default="ONE_COLUMN",
                        max_length=20,
                    ),
                ),
                (
                    "style_size",
                    models.CharField(
                        choices=[
                            ("FULL_HEIGHT", "full height"),
                            ("FULL_WEIGHT", "full weight"),
                        ],
                        default="FULL_HEIGHT",
                        max_length=20,
                    ),
                ),
                (
                    "style_side",
                    models.CharField(
                        choices=[
                            ("LEFT", "left"),
                            ("CENTER", "center"),
                            ("RIGHT", "right"),
                        ],
                        default="LEFT",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "photo",
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.CreateModel(
            name="PhotoPositions",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("columns", models.JSONField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileElement",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=photos.models.upload_to,
                        verbose_name="file",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("positioned", "positioned at last configuration"),
                            ("unpositioned", "not positioned"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "style_size",
                    models.IntegerField(
                        choices=[(0, "full height"), (1, "full width")], default=0
                    ),
                ),
                (
                    "style_side",
                    models.IntegerField(
                        choices=[(0, "left"), (1, "center"), (2, "right")], default=0
                    ),
                ),
                ("order", models.IntegerField(unique=True)),
                (
                    "row",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="photos.filerow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
