# Generated by Django 4.1.7 on 2023-08-30 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileelement",
            name="order",
        ),
    ]
