# Generated by Django 4.1.7 on 2023-08-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_remove_fileelement_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filerow",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
