# Generated by Django 4.1.7 on 2023-06-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0004_remove_photopositions_column_first_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photopositions",
            name="positions",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
