# Generated by Django 4.1.7 on 2023-06-12 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0005_alter_photopositions_positions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="column",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="order",
        ),
    ]
