# Generated by Django 4.1.7 on 2023-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0009_remove_photo_created_remove_photo_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="column_id",
            field=models.IntegerField(default=1),
        ),
    ]
