# Generated by Django 4.1.7 on 2023-07-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0010_photo_column_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
