# Generated by Django 4.1.7 on 2023-08-06 10:50

import django.core.validators
from django.db import migrations, models
import photos.models
import photos.utils.photo_utils


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0013_alter_photo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                storage=photos.utils.photo_utils.CustomFileSystemStorage(),
                upload_to=photos.models.upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(["jpg", "jpeg"])
                ],
                verbose_name="photos",
            ),
        ),
    ]
