# Generated by Django 4.1.7 on 2023-08-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0016_photo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="style_column",
            field=models.CharField(
                choices=[(0, "ONE_COLUMN"), (1, "TWO_COLUMNS"), (2, "THREE_COLUMNS")],
                default=0,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="style_size",
            field=models.CharField(
                choices=[(0, "FULL_HEIGHT"), (1, "FULL_WEIGHT")],
                default=0,
                max_length=20,
            ),
        ),
    ]
