# Generated by Django 4.1.7 on 2023-08-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0017_photo_style_column_photo_style_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="style_side",
            field=models.CharField(
                choices=[(0, "LEFT"), (1, "CENTER"), (2, "RIGHT")],
                default=0,
                max_length=20,
            ),
        ),
    ]
