# Generated by Django 4.1.7 on 2023-08-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0018_photo_style_side"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="style_column",
            field=models.CharField(
                choices=[
                    ("ONE_COLUMN", "ONE_COLUMN"),
                    ("TWO_COLUMNS", "TWO_COLUMNS"),
                    ("THREE_COLUMNS", "THREE_COLUMNS"),
                ],
                default="ONE_COLUMN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="style_side",
            field=models.CharField(
                choices=[("LEFT", "LEFT"), ("CENTER", "CENTER"), ("RIGHT", "RIGHT")],
                default="LEFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="style_size",
            field=models.CharField(
                choices=[
                    ("FULL_HEIGHT", "FULL_HEIGHT"),
                    ("FULL_WEIGHT", "FULL_WEIGHT"),
                ],
                default="FULL_HEIGHT",
                max_length=20,
            ),
        ),
    ]
