# Generated by Django 4.1.7 on 2023-08-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0019_alter_photo_style_column_alter_photo_style_side_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="style_column",
            field=models.CharField(
                choices=[
                    ("ONE_COLUMN", "one_column"),
                    ("TWO_COLUMNS", "two_columns"),
                    ("THREE_COLUMNS", "three_columns"),
                ],
                default="ONE_COLUMN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="style_side",
            field=models.CharField(
                choices=[("LEFT", "left"), ("CENTER", "center"), ("RIGHT", "right")],
                default="LEFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="style_size",
            field=models.CharField(
                choices=[
                    ("FULL_HEIGHT", "full_height"),
                    ("FULL_WEIGHT", "full_weight"),
                ],
                default="FULL_HEIGHT",
                max_length=20,
            ),
        ),
    ]
