# Generated by Django 4.1.7 on 2023-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_photo_column_photo_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoPositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_first", models.JSONField()),
                ("column_second", models.JSONField()),
                ("column_third", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="photo",
            name="created",
            field=models.DateField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
    ]
