# Generated by Django 4.1.7 on 2023-07-21 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("uuid_object", models.UUIDField(verbose_name="ID of object")),
                ("previous_state", models.JSONField(verbose_name="Previous state")),
                ("current_state", models.JSONField(verbose_name="Current state")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
