name: coverage-example

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches:
      - main
      - develop
      - master
      - dev

  push:
    branches:
      - main
      - develop
      - master
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: Build the Stack
        run: docker-compose build
      - name: Tear down the Stack
        run: docker-compose down

  pytest-coverage:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: Run DB Migrations
        run: docker-compose run --rm backend python manage.py migrate
      - name: Run Django Tests
        run: docker-compose run backend coverage run -m pytest
      - name: Generate coverage.lcov
        run: docker-compose -f docker-compose.yml run backend coverage lcov
      - name: Tear down the Stack
        run: docker-compose down
      - name: Coveralls Parallel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: "./backend/coverage.lcov"
          base-path: "./backend"
          flag-name: run-1
          parallel: true
        uses: coverallsapp/github-action@v2